#!/usr/bin/env bash
# Generate STRUCTURE.md with tree output (excludes build artifacts, deps, etc.)
# Usage: treegen.sh [--no-stage] [DIR]
#   --no-stage  Do not stage STRUCTURE.md after updating it.
#   DIR         Target directory (default: current directory).

set -euo pipefail

# Keep tree ordering and UTF-8 connector parsing independent from the caller.
export LC_ALL=C.UTF-8

# filetree-pro.exclude + py/db/logs + otel/dagster/grafana runtime (var, .nux, .telemetry, compute_logs)
TREE_IGNORE='.git|.gitnexus|.venv-tools|.claude|node_modules|dist|build|out|.venv|venv|env|.env|target|bin|obj|.vs|.idea|__pycache__|__none__|mypy_cache|.mypy_cache|*.pyc|*.log|*.tmp|*.cache|.ruff_cache|uncommitted|index_*|chunks|wal|*.db|*.db-shm|*.db-wal|logs|var|.nux|.telemetry|compute_logs'

NO_STAGE=0
TARGET_DIR="."
target_set=0

while [[ $# -gt 0 ]]; do
	case "$1" in
	--no-stage)
		NO_STAGE=1
		;;
	-*)
		echo "treegen.sh: unknown option: $1" >&2
		exit 2
		;;
	*)
		if [[ "$target_set" -eq 1 ]]; then
			echo "treegen.sh: only one target directory may be provided." >&2
			exit 2
		fi
		TARGET_DIR="$1"
		target_set=1
		;;
	esac
	shift
done

TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"
ROOT_NAME="$(basename "$TARGET_DIR")"

if ! command -v tree &>/dev/null; then
	echo "treegen.sh: 'tree' not found. Install it (e.g. apt install tree / brew install tree)." >&2
	exit 1
fi

OUTPUT="$TARGET_DIR/STRUCTURE.md"
RAW_TREE="$(cd "$TARGET_DIR" && tree -a -I "$TREE_IGNORE" --dirsfirst -n --noreport --charset UTF-8 -F . 2>/dev/null)" || true

# Add icons: 📁 dirs, 📝 .md, 🐍 .py, 🐳 Docker/hcl, ⚙️ config, 🔒 lock, 🐚 sh/zsh, 🗄️ sql, 📊 csv, 📕 pdf, 🖼️ img, 📓 ipynb, 📋 xml/log, 🪟 ps1, 🔨 make, 📄 rest
# Prefix "── " is 3 chars (U+2500 U+2500 space), so name starts at RSTART+3
TREE_OUT="$(echo "$RAW_TREE" | awk '
  /^\.\/$/ { print "📁 ."; next }
  /\/$/  { sub(/\/$/, ""); sub(/── /, "── 📁 "); print; next }
  {
    if (match($0, /── .*$/)) {
      name = substr($0, RSTART+3, RLENGTH-3)
      gsub(/\*$/, "", name)
      if (name ~ /\.(md|markdown)$/)             icon = "📝"
      else if (name ~ /\.py$/)                   icon = "🐍"
      else if (name == "Dockerfile" || name ~ /^Dockerfile\./) icon = "🐳"
      else if (name ~ /\.(json|yml|yaml|toml)$/) icon = "⚙️"
      else if (name ~ /\.lock$/)                 icon = "🔒"
      else if (name ~ /\.(js|mjs|ts|tsx|jsx)$/)  icon = "📜"
      else if (name ~ /\.(sh|bash|zsh)$/)        icon = "🔧"
      else if (name ~ /\.sql$/)                  icon = "🗄️"
      else if (name ~ /\.csv$/)                  icon = "📊"
      else if (name ~ /\.hcl$/)                  icon = "🐳"
      else if (name ~ /\.pdf$/)                  icon = "📕"
      else if (name ~ /\.svg$/)                  icon = "🖼️"
      else if (name ~ /\.(jpg|jpeg|gif)$/)       icon = "🖼️"
      else if (name ~ /\.ipynb$/)                icon = "📓"
      else if (name ~ /\.txt$/)                  icon = "📄"
      else if (name ~ /\.ini$/)                  icon = "⚙️"
      else if (name ~ /\.xml$/)                  icon = "📋"
      else if (name ~ /\.log$/)                  icon = "📋"
      else if (name ~ /\.ps1$/)                  icon = "🪟"
      else if (name ~ /\.mk$/ || name ~ /^[Mm]akefile$/) icon = "🔨"
      else                                      icon = "📄"
      sub(/── .*$/, "── " icon " " name)
    }
    print
  }
')"

write_structure() {
	local destination="$1"
	{
		echo "# File Tree: $ROOT_NAME"
		echo ""
		echo "**Generated by:** \`scripts/treegen.sh\`"
		echo "**Root Path:** \`$TARGET_DIR\`"
		echo ""
		echo "\`\`\`"
		echo "$TREE_OUT"
		echo "\`\`\`"
	} >"$destination"
}

stage_structure() {
	if [[ "$NO_STAGE" -eq 0 ]] && git -C "$TARGET_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
		git -C "$TARGET_DIR" add STRUCTURE.md
	fi
}

TEMP_OUTPUT="$(mktemp "${TARGET_DIR}/.STRUCTURE.md.tmp.XXXXXX")"
trap 'rm -f "$TEMP_OUTPUT"' EXIT
write_structure "$TEMP_OUTPUT"

if [[ -f "$OUTPUT" ]] && cmp -s "$TEMP_OUTPUT" "$OUTPUT"; then
	echo "Unchanged: $OUTPUT"
	exit 0
fi

mv "$TEMP_OUTPUT" "$OUTPUT"
trap - EXIT

stage_structure
echo "Written: $OUTPUT"
